environments:
  saas-mumbai:
    values:
    - "./env-values/environment.yaml.gotmpl"
    - "./env-values/saas-mumbai/environment.yaml.gotmpl"
  nonprod-oregon:
    values:
    - "./env-values/environment.yaml.gotmpl"
    - "./env-values/nonprod-oregon/environment.yaml.gotmpl"
  prod-singapore:
    values:
    - "./env-values/environment.yaml.gotmpl"
    - "./env-values/prod-singapore/environment.yaml.gotmpl"
  prod-sydney:
    values:
    - "./env-values/environment.yaml.gotmpl"
    - "./env-values/prod-sydney/environment.yaml.gotmpl"
  prod-hongkong:
    values:
    - "./env-values/environment.yaml.gotmpl"
    - "./env-values/prod-hongkong/environment.yaml.gotmpl"

helmDefaults:
  wait: true
  timeout: 600
  recreatePods: false
  force: false
  disableOpenAPIValidation: true

releases:
  - name: helm-guestbook
    labels:
      service: helm-guestbook
      shared: true
    chart: ./charts/helm-guestbook
    missingFileHandler: Warn
    values:
      - "./charts/helm-guestbook/values/values.yaml.gotmpl"
      - "./charts/helm-guestbook/values/{{ .Environment.Name }}/values.yaml.gotmpl"

  - name: backend
    labels:
      service: backend
      shared: true
    chart: ./charts/backend
    missingFileHandler: Warn
    values:
      - "./charts/backend/values/values.yaml.gotmpl"
      - "./charts/backend/values/{{ .Environment.Name }}/values.yaml.gotmpl"
