releases:
  - name: helm-guestbook
    labels:
      service: helm-guestbook
      shared: true
    namespace: argo-test
    wait: false
    chart: ./charts/helm-guestbook
    missingFileHandler: Warn
    version: 2.15.3
    values:
      - "./charts/helm-guestbook/values/values.yaml"
      - "./charts/helm-guestbook/values/stable-saas-v2/values.yaml.gotmpl"
