apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Dakshjain1/argo-application-test.git
      revision: HEAD
      directories:
      - path: charts/*/*/*
  template:
    metadata:
      name: '{{path[1]}}' 
    spec:
      project: default
      source:
        repoURL: https://github.com/Dakshjain1/argo-application-test.git
        targetRevision: HEAD
        path: 'charts/{{path[1]}}'
        helm:
          valueFiles:
            - 'values/{{path.basename}}/values.yaml'
            - 'values/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:      
        - Validate=true
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - RespectIgnoreDifferences=true 
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2  
            maxDuration: 3m
