apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Dakshjain1/argo-application-test.git
      revision: HEAD
      files:
      - path: "charts/*/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{.cluster.name}}-{{.cluster.namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Dakshjain1/argo-application-test.git
        targetRevision: HEAD
        path: 'charts/{{index .path.segments 1}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - 'values/values.yaml'
            - 'values/{{.cluster.name}}/values.yaml.gotmpl'
            - 'values/{{.cluster.name}}/{{.cluster.namespace}}/values.yaml.gotmpl'
          values: |
            image:
              tag: {{ readFile "../../../../versions/backend_nonprod.yaml" | fromYaml | pluck "backend_docker_image_tag"  | first | default "latest" | toYaml }}
      destination:
        server: '{{.cluster.server}}'
        namespace: '{{.cluster.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:      
        - Validate=true
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - RespectIgnoreDifferences=true 
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2  
            maxDuration: 3m
