apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dakshjain1/argo-application-test.git
    path: ./charts/helm-guestbook
    targetRevision: HEAD
    plugin:
      name: plugin
      env:
        - name: SELECTOR
          value: helm-guestbook
        - name: FILE
          value: ../../helmfile.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'argo-test'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true 
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2  
        maxDuration: 3m
