apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Dakshjain1/argo-application-test.git
      revision: HEAD
      files:
      - path: 'charts/*/cluster-config/**/config.json'
  template:
    metadata:
      name: '{{path[1]}}-{{cluster.env}}-{{cluster.namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Dakshjain1/argo-application-test.git
        targetRevision: HEAD
        path: './charts/{{path[1]}}'
        plugin:
          name: plugin
          env:
          - name: ENV
            value: '{{cluster.env}}'
          - name: SELECTOR
            value: '{{path[1]}}'
          - name: FILE
            value: ../../helmfile.yaml
      destination:
        server: '{{cluster.server}}'
        namespace: '{{cluster.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - Validate=true
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
